databases:
  - name: my-mysql-db
    plan: free

services:
  - type: web
    name: task-manager-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: my-mysql-db
          property: connectionString
