-- AlterTable
ALTER TABLE `tasks` MODIFY `name` VARCHAR(50) NOT NULL,
    MODIFY `created_at` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFY `category` INTEGER NULL;

-- AlterTable
ALTER TABLE `tasks_category` ADD COLUMN `archive` TINYINT NULL DEFAULT 0,
    MODIFY `created_at` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE `users` MODIFY `created_at` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFY `updated_at` TIMESTAMP(0) NULL;
